trigger:
- main

pool: 'MyLocalPool'

variables:
- group: github-att

stages:
- stage: Build
  displayName: 'Build and Push Stage'
  jobs:
  - job: Build
    displayName: 'Build and Push to ACR'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-service-connection'
        repository: 'ranacse/sales-dashboard-v1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: UpdateManifest
  displayName: 'Update Kubernetes Manifest Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: UpdateGit
    displayName: 'Update Manifest Repo'
    steps:
    - powershell: |
        git config --global user.email "saif99cse@gmail.com"
        git config --global user.name "saif99cse"
        
        # সেকেন্ড ম্যানিফেস্ট রিপোজিটরি ক্লোন
        git clone https://$(token)@github.com/ranacse/html-manifest-repo.git
        cd html-manifest-repo
        
        # উইন্ডোজ পাওয়ারশেল দিয়ে কুবারনেটিস ফাইল আপডেট (ভিডিওর sed এর ফাইনাল উইন্ডোজ রূপ)
        (Get-Content deployment.yaml) -replace 'ranacse/sales-dashboard-v1:40
        
        # গিটহাবে ফাইনাল পুশ
        git add deployment.yaml
        git commit -m "Update deployment spec image tag to $(Build.BuildId)"
        git push origin main
      displayName: 'Update Git Image Tag (Windows Native)'
